apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-my-release-redis-cluster-pv-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis-data-my-release-redis-cluster-data-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-my-release-redis-cluster-pv-1
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis-data-my-release-redis-cluster-data-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-my-release-redis-cluster-pv-2
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis-data-my-release-redis-cluster-data-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-my-release-redis-cluster-pv-3
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis-data-my-release-redis-cluster-data-3


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-my-release-redis-cluster-pv-4
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis-data-my-release-redis-cluster-data-4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-my-release-redis-cluster-pv-5
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/redis-data-my-release-redis-cluster-data-5
    